### ISSUE TITLE
user hostmask exception

### ISSUE THREAD

**Issue by gnowxilef** [rfw/kochira#38]
```
[E 150829 00:05:22 client:145] Hook processing failed
    Traceback (most recent call last):
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/pydle/async.py", line 34, in handle_future
        result = gen.send(future.result())
    StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/kochira-0.0-py3.4.egg/kochira/client.py", line 136, in _coro
        r = hook(ctx, *args, **kwargs)
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/pydle/async.py", line 50, in wrapper
        result = next(gen)
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/kochira-0.0-py3.4.egg/kochira/service.py", line 204, in _command_handler
        for permission in permissions):
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/kochira-0.0-py3.4.egg/kochira/service.py", line 204, in <genexpr>
        for permission in permissions):
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/kochira-0.0-py3.4.egg/kochira/auth.py", line 33, in has_permission
        if matcher(mask, user) and (permission in permissions or "admin" in permissions):
      File "/home/w/wa/waf/ve/lib/python3.4/site-packages/kochira-0.0-py3.4.egg/kochira/auth.py", line 21, in <lambda>
        None: lambda hostmask, user: fnmatch.fnmatch(user.hostmask, hostmask)
    AttributeError: 'str' object has no attribute 'hostmask'
```

probably came about due to: https://github.com/rfw/kochira/commit/fba80dc61ddc8c3ca0eca96820222af3da326b3c and https://github.com/rfw/kochira/commit/f727d0464ba9c994c58dfa0ebca7ea93881faca3

**Comment by rfw** [comment]
sorry i suck, committed to wrong branch :(
